name: Linking jobs example

on: 
  workflow_dispatch:

jobs:
  linking-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Linking jobs
        uses: samuel-bland/GithubHelloWorld2/.github/workflows/hello-world.yaml@main
