name: Linking jobs example

on: 
  workflow_dispatch:

jobs:
  call-workflow-1:
    uses: ./.github/workflows/linking-jobs-called.yaml
    with:
      username: Samuel
    
  call-workflow-2:
    uses: ./.github/workflows/linking-jobs-called.yaml
    with:
      username: Greg

